In [3]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.layers import Conv2D,MaxPooling2D, Dropout,BatchNormalization
#Empty neural network model
model=Sequential()
model.add(Conv2D(64,(3,3), input_shape=(50,50,1),kernel_initializer='orthogonal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32,(3,3),kernel_initializer='orthogonal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(1000, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


C:\Users\Sandalika\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 48, 48, 64)     │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 48, 48, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation (Activation)         │ (None, 48, 48, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 24, 24, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 22, 22, 32)     │        18,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 22, 22, 32)     │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_1 (Activation)       │ (None, 22, 22, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 11, 11, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 3872)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 3872)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1000)           │     3,873,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │       128,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2)              │           130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,029,002 (15.37 MB)

 Trainable params: 4,028,810 (15.37 MB)

 Non-trainable params: 192 (768.00 B)

In [7]:
model.load_weights(r'C:\Users\Sandalika\Documents\deep learning workshop\model-047.keras')


C:\Users\Sandalika\anaconda3\Lib\site-packages\keras\src\saving\saving_lib.py:576: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 34 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [17]:
import os
import cv2
import numpy as np

test_path = r'C:\Users\Sandalika\Documents\deep learning workshop\test_imgs'

img_names=os.listdir(test_path)
category_dict={0:'Cat', 1:'Dog'}
for img_name in img_names:
    img=cv2.imread(os.path.join(test_path,img_name))
    h,w=img.shape[0:2]

#presprocessing as done for the training images
    test_img=cv2.resize(img,(50,50))
    test_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    test_img=test_img/255
    test_img=test_img.reshape(1,50,50,1)#after converting a gray,shape becomes 2D->(50,50),So we need to make it 4D, the first '1' shows that one image at a time is considered and last '1' says this gray image should converted to 3D

    results=model.predict(test_img)# here you will get a probability(predict results will give a probability for cat and dog)
    label=np.argmax(results,axis=1)[0] #fins the index of the maxium value
    acc=int(np.max(results,axis=1)[0]*100)#accuracy was in probabilty, so convert it to a whole number

    print(results,label,category_dict[label],acc)

    img[0:50, 0:w] = [0, 255, 0]
    cv2.putText(img, category_dict[label], (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)
    cv2.putText(img, str(acc) + "%", (120, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)

    cv2.imshow('LIVE',img)
    k = cv2.waitKey(1000)  # Shorter wait time for more responsive display
    if(k==27):
        break
cv2.destroyAllWindows()

    
    

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
[[0.55936027 0.44063973]] 0 Cat 55
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[0.20671001 0.79328996]] 1 Dog 79
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[0.3370502 0.6629498]] 1 Dog 66
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.2388627  0.76113737]] 1 Dog 76
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.5054451  0.49455488]] 0 Cat 50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[0.12207427 0.8779257 ]] 1 Dog 87
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.19222943 0.8077705 ]] 1 Dog 80
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0.2054756  0.79452443]] 1 Dog 79
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.5152528 0.4847471]] 0 Cat 51
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.6901021 0.3098979]] 0 Cat 69
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0.22903986 0.7709601 ]] 1 Dog 77
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.28255978 0.7174402 ]] 1 Dog 71
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0.81054497 0.189455  ]] 0 Cat 81
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[0.86006    0.1399